### ISSUE TITLE
Minified bundled javascript.

### ISSUE THREAD

**Issue by sergiotarxz** [bludit-themes/micro#9]
Distributing minified javascript in git may not be the best idea since if a bug is discovered in the bundled javascript will be difficult to know the version of the javascript and how the bug happens. I suggest to generate the minified javascript of everything if required by the blog owner knowing it makes more difficult to diagnose bugs.

**Comment by clickwork-git** [comment]
I see there no problem. If you open the file you see the version.

Furthermore it's a script developed by a third party and implemented "as it is".

Debugging should be part of the repository of the author, and if this is not possible of a forked version, which doesn't exist at the moment.

**Comment by sergiotarxz** [comment]
Then I am closing this.
